- Error escalation improved, SU failover recovery action added - Most runtime attributes in the inf. model calculated in runtime from   more fundamental information. (improves consistency) - sg_assign_si can now recalculate workloads considering existing   assignments - Logging improvements, similar to what is required as notification in   AMF spec. - CLC-CLI INSTANTIATE now exits aisexec when it fails (should later be   sent as an NTF alarm) - CLC-CLI CLEANUP correctly handles already terminated processes - testamf1.c printouts removed for normal operation - Iterator functions for SI/CSI assignments
git-svn-id: http://svn.fedorahosted.org/svn/corosync/trunk@1108 fd59a12c-fef9-0310-b244-a6a79926bd2f

diff --git a/test/clc_cli_script b/test/clc_cli_script
--- a/test/clc_cli_script
+++ b/test/clc_cli_script
@@ -33,7 +33,7 @@
 # It may be modified to do any action desired.
 
 instantiate() {
-	echo clc_cli_script instantiating component $SA_AMF_COMPONENT_NAME $1
+#	echo clc_cli_script instantiating component $SA_AMF_COMPONENT_NAME $1
 	./openais-instantiate $1
 	exit $?
 }
@@ -44,7 +44,8 @@ terminate() {
 	else
 		PIDFILEPATH=/tmp
 	fi
-	echo clc_cli_script terminating up component $SA_AMF_COMPONENT_NAME on PID `cat $PIDFILEPATH/openais_cleanup_$SA_AMF_COMPONENT_NAME`
+	echo clc_cli_script terminating component $SA_AMF_COMPONENT_NAME on PID \
+	`cat $PIDFILEPATH/openais_cleanup_$SA_AMF_COMPONENT_NAME`
 	kill -15 `cat $PIDFILEPATH/openais_cleanup_$SA_AMF_COMPONENT_NAME`
 	exit $?
 }
@@ -55,9 +56,15 @@ cleanup() {
 	else
 		PIDFILEPATH=/tmp
 	fi
-	echo clc_cli_script cleaning up component $SA_AMF_COMPONENT_NAME on PID `cat $PIDFILEPATH/openais_cleanup_$SA_AMF_COMPONENT_NAME`
+#	echo clc_cli_script cleaning up component $SA_AMF_COMPONENT_NAME on PID \
+#	`cat $PIDFILEPATH/openais_cleanup_$SA_AMF_COMPONENT_NAME`
 	kill -9 `cat $PIDFILEPATH/openais_cleanup_$SA_AMF_COMPONENT_NAME`
-	exit $?
+	STATUS=$?
+	if [ $STATUS == 1 ]; then
+		exit 0
+	else
+		exit $STATUS
+	fi
 }
 
 usage() {
